# Generated by Django 4.2 on 2023-07-02 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('assigned_name', models.CharField(max_length=50)),
                ('date_assigned', models.DateField(default=datetime.date.today)),
                ('date_due', models.DateField()),
                ('task_details', models.TextField()),
                ('task_importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('completion_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], max_length=10)),
            ],
        ),
    ]
