# Generated by Django 4.2 on 2023-07-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
